In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key
g_key

'AIzaSyC3POlJP0Wgrbn8LA9mI5XU6YQQVoPtoGk'

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Mataura,NZ,2022-08-01 20:51:30,-46.1927,168.8643,44.47,95,98,7.61
1,1,Abha,SA,2022-08-01 20:51:31,18.2164,42.5053,61.05,88,40,0.00
2,2,Cape Town,ZA,2022-08-01 20:48:38,-33.9258,18.4232,54.91,78,0,4.61
3,3,Koltubanovskiy,RU,2022-08-01 20:51:31,52.9407,52.0269,62.44,90,0,5.48
4,4,Uarini,BR,2022-08-01 20:51:32,-2.9900,-65.1083,79.50,87,99,2.44

In [3]:
# Get the data types
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)
gmaps

In [8]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []


# 1. Assign the locations to an array of latitude and longitude pairs.
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]

# 2. Assign the weight variable to some values.
# an array of length eqaul to the locations array length
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]

# 3. Assign the fiugre variable to the gmaps.figure() attribute.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp,0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)

# 5. Add the heatmap layer
fig.add_layer(heat_layer)

# 6. Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]

# 2. Assign the weight variable to some values.
# an array of length eqaul to the locations array length
# Get the maximum temperature.
humidity = city_data_df["Humidity"]

# 3. Assign the fiugre variable to the gmaps.figure() attribute.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

# 5. Add the heatmap layer
fig.add_layer(heat_layer)

# 6. Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]

# 2. Assign the weight variable to some values.
# an array of length eqaul to the locations array length
# Get the maximum temperature.
clouds = city_data_df["Cloudiness"]

# 3. Assign the fiugre variable to the gmaps.figure() attribute.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

# 5. Add the heatmap layer
fig.add_layer(heat_layer)

# 6. Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# Heatmap of Wind Speed
locations = city_data_df[["Lat", "Lng"]]

# 2. Assign the weight variable to some values.
# an array of length eqaul to the locations array length
# Get the maximum temperature.
wind = city_data_df["Wind Speed"]

# 3. Assign the fiugre variable to the gmaps.figure() attribute.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

# 5. Add the heatmap layer
fig.add_layer(heat_layer)

# 6. Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [14]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"]<= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
4,4,Uarini,BR,2022-08-01 20:51:32,-2.9900,-65.1083,79.50,87,99,2.44
11,11,Avarua,CK,2022-08-01 20:51:35,-21.2078,-159.7750,78.85,61,20,18.41
18,18,Cabedelo,BR,2022-08-01 20:51:38,-6.9811,-34.8339,79.47,80,6,16.22
26,26,Katsuura,JP,2022-08-01 20:51:41,35.1333,140.3000,80.19,89,100,10.13
34,34,Huangpi,CN,2022-08-01 20:51:45,30.8845,114.3779,84.31,79,0,6.71
36,36,Gat,IL,2022-08-01 20:51:46,31.6100,34.7642,82.40,100,0,1.92
38,38,Puerto Ayora,EC,2022-08-01 20:51:47,-0.7393,-90.3518,82.36,96,78,5.01
41,41,Jacareacanga,BR,2022-08-01 20:51:37,-6.2222,-57.7528,83.16,60,99,4.29
43,43,Padilla,CO,2022-08-01 20:51:49,3.2204,-76.3139,85.57,68,84,2.10
49,49,Kahului,US,2022-08-01 20:52:51,20.8947,-156.4700,82.42,69,40,12.66

In [18]:
preferred_cities_df.count()

City_ID       206
City          206
Country       206
Date          206
Lat           206
Lng           206
Max Temp      206
Humidity      206
Cloudiness    206
Wind Speed    206
dtype: int64

In [19]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"]= ""
hotel_df.head(10)

            City Country  Max Temp      Lat       Lng Hotel Name
4         Uarini      BR     79.50  -2.9900  -65.1083
11        Avarua      CK     78.85 -21.2078 -159.7750
18      Cabedelo      BR     79.47  -6.9811  -34.8339
26      Katsuura      JP     80.19  35.1333  140.3000
34       Huangpi      CN     84.31  30.8845  114.3779
36           Gat      IL     82.40  31.6100   34.7642
38  Puerto Ayora      EC     82.36  -0.7393  -90.3518
41  Jacareacanga      BR     83.16  -6.2222  -57.7528
43       Padilla      CO     85.57   3.2204  -76.3139
49       Kahului      US     82.42  20.8947 -156.4700

In [20]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [22]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [23]:
hotel_df

,City,Country,Max Temp,Lat,Lng,Hotel Name
4,Uarini,BR,79.50,-2.9900,-65.1083,
11,Avarua,CK,78.85,-21.2078,-159.7750,Paradise Inn
18,Cabedelo,BR,79.47,-6.9811,-34.8339,Pousada Camboinha
26,Katsuura,JP,80.19,35.1333,140.3000,Katsuura Hotel Mikazuki
34,Huangpi,CN,84.31,30.8845,114.3779,Xinxing Lidu Hotel
...,...,...,...,...,...,...
563,Maniwaki,CA,80.20,46.3834,-75.9660,Centre Chateau Logue
566,Maceio,BR,78.24,-9.6658,-35.7353,Hotel Ponta Verde Maceió
570,San Francisco,US,81.23,37.7749,-122.4194,Edwardian Hotel
573,Makat,KZ,81.68,47.6469,53.3463,Umit
582,Santarem,BR,84.33,-2.4431,-54.7083,Hotel Imperador

In [24]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [25]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [29]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]


# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))