## Deliverable 3. Create a Travel Itinerary Map.

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [4]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,9,Guider,CM,78.94,overcast clouds,9.9342,13.9486,"AUBERGE LA GRACE , GÉRANT : OUDAWAREME BALTHAZAR"
1,11,Yar-Sale,RU,66.85,clear sky,66.8333,70.8333,Yalemd
2,13,Avarua,CK,71.65,broken clouds,-21.2078,-159.7750,Paradise Inn
3,15,Victoria,HK,84.96,overcast clouds,22.2855,114.1577,Mini Central
4,16,Ureki,GE,75.16,overcast clouds,41.9956,41.7786,Hotel Ritsa

In [7]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [9]:
# 4a. Add a marker layer for each city to the map.
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [14]:
preferred_cities_df = vacation_df.loc[(vacation_df["Country"] == "IT")]
preferred_cities_df.head(10)

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
67,166,Vieste,IT,80.24,clear sky,41.8825,16.1750,Hotel Falcone
132,287,Syracuse,IT,83.57,clear sky,37.0881,15.2792,Hotel Posta
136,292,Crotone,IT,78.19,clear sky,39.0851,17.1178,Helios Hotel
216,436,Campobasso,IT,79.81,broken clouds,41.6333,14.5833,Tre Archi
244,489,Pachino,IT,82.83,scattered clouds,36.7186,15.0907,Il Veliero
300,603,Ortona,IT,79.86,overcast clouds,42.3496,14.4039,La Casa del Palombaro
326,650,Pontecorvo,IT,80.98,light rain,41.4616,13.6667,Hotel Ristorante Liolà

In [16]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = "Pontecorvo"
vacation_end = "Pontecorvo"
vacation_stop1 = "Ortona"
vacation_stop2 = "Vieste"
vacation_stop3 = "Crotone"

vacation_start = vacation_df.loc[(vacation_df["City"] == vacation_start)]
vacation_end = vacation_df.loc[(vacation_df["City"] == vacation_end)]
vacation_stop1 = vacation_df.loc[(vacation_df["City"] == vacation_stop1)]
vacation_stop2 = vacation_df.loc[(vacation_df["City"] == vacation_stop2)]
vacation_stop3 = vacation_df.loc[(vacation_df["City"] == vacation_stop3)]

In [17]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[["Lat", "Lng"]].to_numpy()[0]
end = vacation_end[["Lat", "Lng"]].to_numpy()[0]
stop1 = vacation_stop1[["Lat", "Lng"]].to_numpy()[0]
stop2 = vacation_stop2[["Lat", "Lng"]].to_numpy()[0]
stop3 = vacation_stop3[["Lat", "Lng"]].to_numpy()[0]

In [26]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
travel_route = gmaps.directions_layer(start, end, waypoints=[stop1,stop2,stop3], travel_mode="BICYCLING" or "BICYCLING" or "WALKING")
fig.add_layer(travel_route)
fig

Figure(layout=FigureLayout(height='420px'))

In [19]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3, vacation_end],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,650,Pontecorvo,IT,80.98,light rain,41.4616,13.6667,Hotel Ristorante Liolà
1,603,Ortona,IT,79.86,overcast clouds,42.3496,14.4039,La Casa del Palombaro
2,166,Vieste,IT,80.24,clear sky,41.8825,16.1750,Hotel Falcone
3,292,Crotone,IT,78.19,clear sky,39.0851,17.1178,Helios Hotel
4,650,Pontecorvo,IT,80.98,light rain,41.4616,13.6667,Hotel Ristorante Liolà

In [20]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp}</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [32]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure()
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))